package com.serviceops.common.exception;

public enum ErrorCode {
    INVALID_CREDENTIALS,
    ACCOUNT_LOCKED,
    ACCOUNT_INACTIVE,
    DUPLICATE_DATA,
    INVALID_STATE,
    VALIDATION_ERROR,
    RESOURCE_NOT_FOUND,
    FORBIDDEN,
    RESET_TOKEN_INVALID,
    TWO_FACTOR_INVALID,
    INTERNAL_ERROR
}
