import {
  Pencil, UserCog, Lock, Unlock, Eye, EyeOff, RotateCcw, MoreVertical,
  Users, UserCheck, User, UserMinus, Shield, ShieldOff, CheckCircle2, AlertTriangle,
  Info, ClipboardList, Clock, History, X, Globe, ListTree, Building2, Folder,
  Search, RefreshCw, Settings2, MoveVertical, ArrowDown, Plus, Trash2, Mail, Phone,
  Calendar, Banknote, Tag, BarChart3, Bell, Briefcase, Target, Save, Upload, Download,
  Landmark, Receipt, Link2, KeyRound, Star, Wrench, MapPin, Sparkles, FileText,
  HelpCircle, LogOut, PanelLeft, ChevronDown, Hash, Copy, GitMerge,
} from 'lucide-react';

/**
 * Bộ icon dùng chung cho TOÀN BỘ frontend — dựa trên Lucide (MIT, https://lucide.dev), bộ icon nét
 * mảnh chuyên nghiệp dùng trong nhiều sản phẩm SaaS thật (Linear, Vercel, Notion...), thay cho icon
 * tự vẽ tay trước đó. Kích thước/độ dày nét mặc định ở đây chỉ là fallback — mọi nơi dùng đã bọc
 * icon trong span có CSS quy định width/height riêng (xem DESIGN.md § Icons), nên strokeWidth thống
 * nhất là điều quan trọng nhất để cả bộ trông liền mạch.
 */
const STROKE = 1.75;

export const ICONS = {
  edit: <Pencil strokeWidth={STROKE} />,
  role: <UserCog strokeWidth={STROKE} />,
  lock: <Lock strokeWidth={STROKE} />,
  unlock: <Unlock strokeWidth={STROKE} />,
  eye: <Eye strokeWidth={STROKE} />,
  eyeOff: <EyeOff strokeWidth={STROKE} />,
  resetTwoFactor: <RotateCcw strokeWidth={STROKE} />,
  more: <MoreVertical strokeWidth={STROKE} />,
  users: <Users strokeWidth={STROKE} />,
  userCheck: <UserCheck strokeWidth={STROKE} />,
  user: <User strokeWidth={STROKE} />,
  userMinus: <UserMinus strokeWidth={STROKE} />,
  shield: <Shield strokeWidth={STROKE} />,
  shieldOff: <ShieldOff strokeWidth={STROKE} />,
  checkCircle: <CheckCircle2 strokeWidth={STROKE} />,
  alertTriangle: <AlertTriangle strokeWidth={STROKE} />,
  info: <Info strokeWidth={STROKE} />,
  clipboardList: <ClipboardList strokeWidth={STROKE} />,
  clock: <Clock strokeWidth={STROKE} />,
  history: <History strokeWidth={STROKE} />,
  close: <X strokeWidth={STROKE} />,
  globe: <Globe strokeWidth={STROKE} />,
  tree: <ListTree strokeWidth={STROKE} />,
  building: <Building2 strokeWidth={STROKE} />,
  folder: <Folder strokeWidth={STROKE} />,
  search: <Search strokeWidth={STROKE} />,
  refresh: <RefreshCw strokeWidth={STROKE} />,
  settings: <Settings2 strokeWidth={STROKE} />,
  moveVertical: <MoveVertical strokeWidth={STROKE} />,
  arrowDown: <ArrowDown strokeWidth={STROKE} />,
  plus: <Plus strokeWidth={STROKE} />,
  trash: <Trash2 strokeWidth={STROKE} />,
  mail: <Mail strokeWidth={STROKE} />,
  phone: <Phone strokeWidth={STROKE} />,
  calendar: <Calendar strokeWidth={STROKE} />,
  money: <Banknote strokeWidth={STROKE} />,
  tag: <Tag strokeWidth={STROKE} />,
  chart: <BarChart3 strokeWidth={STROKE} />,
  bell: <Bell strokeWidth={STROKE} />,
  briefcase: <Briefcase strokeWidth={STROKE} />,
  target: <Target strokeWidth={STROKE} />,
  save: <Save strokeWidth={STROKE} />,
  upload: <Upload strokeWidth={STROKE} />,
  download: <Download strokeWidth={STROKE} />,
  bank: <Landmark strokeWidth={STROKE} />,
  receipt: <Receipt strokeWidth={STROKE} />,
  link: <Link2 strokeWidth={STROKE} />,
  key: <KeyRound strokeWidth={STROKE} />,
  star: <Star strokeWidth={STROKE} />,
  wrench: <Wrench strokeWidth={STROKE} />,
  pin: <MapPin strokeWidth={STROKE} />,
  spark: <Sparkles strokeWidth={STROKE} />,
  document: <FileText strokeWidth={STROKE} />,
  helpCircle: <HelpCircle strokeWidth={STROKE} />,
  logout: <LogOut strokeWidth={STROKE} />,
  panelToggle: <PanelLeft strokeWidth={STROKE} />,
  chevronDown: <ChevronDown strokeWidth={STROKE} />,
  hash: <Hash strokeWidth={STROKE} />,
  copy: <Copy strokeWidth={STROKE} />,
  merge: <GitMerge strokeWidth={STROKE} />,
};
