-- =============================================================================
--  DEPRECATED (2026-09-22) — TRUOC DAY LA 8 CO HOI MAU BO SUNG CHO "DU BAO
--  DOANH THU" (2101..2108), GIO CHI CON LA CLEANUP
-- =============================================================================
--  File nay tung them 8 co hoi de "Phan bo doanh thu ky vong theo thang" trai
--  deu hon, nhung phan lon 8 co hoi do gan voi khach hang KHONG PHAI 2 khach
--  hang sale01 thuc su phu trach (1001, 1002) — dang nhap sale01 thay ten
--  cong ty la, gay hieu nham du lieu seed sai/mo coi (vd "Xay dung cong
--  thong tin khach hang cho ACBank" chi la TEN co hoi tu chon, khach hang
--  that gan vao la 1005, khong phai ACBank). Quyet dinh rut gon toan bo
--  danh sach co hoi mau xuong CHI CON 2 co hoi (xem
--  R__seed_sample_opportunities.sql) nen 8 co hoi nay khong con phu hop.
--
--  File nay VAN GIU LAI (khong xoa khoi dia) chi de mang doan DELETE ben
--  duoi — day la file repeatable (R__), Flyway chi CHAY LAI khi noi dung file
--  thay doi. Neu xoa han file nay khoi repo, checksum cu trong
--  flyway_schema_history van con nguyen o may cac thanh vien khac nen Flyway
--  se KHONG chay lai gi ca khi ho pull code moi — 8 ban ghi rac van nam
--  nguyen trong DB cua ho. Giu file + doi noi dung thanh DELETE la cach duy
--  nhat dam bao MOI NGUOI keo code ve deu tu dong don sach, khong phai chay
--  tay script rieng.
-- ----------------------------------------------------------------------------
DELETE FROM opportunities WHERE id IN (2101, 2102, 2103, 2104, 2105, 2106, 2107, 2108);
